language: node_js

node_js:
  - '10'

before_script:
  - npm i -g lint-md-cli

script:
  - lint-md *.md

after_failure:
  - curl "https://api.day.app/${APIDAYTOKEN}/guanguans.github.io构建失败"

after_success:
  - curl "https://api.day.app/${APIDAYTOKEN}/guanguans.github.io构建成功"
