# theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: title
description: description

show_downloads: true
google_analytics: Your Google Analytics tracking ID

github:
  zip_url: http://example.com/download.zip
  another_url: another value

# Setup
title:        guanguans
tagline:      No practice, no gain in one's wit.
baseurl:      ""
paginate:     1
locale:       "en_US"

# About/contact
author:
  name:       guanguans
  url:        https://guanguans.github.io

# Gems
gems:
  - jekyll-paginate

# Others
markdown: kramdown
