theme: jekyll-theme-cayman

# Setup
title:        Project or Site name
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     3
locale:       "zh_CN"

# About/contact
author:
  name:       琯琯
  url:        https://guanguans.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
