theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Setup
title:        guanguans
tagline:      No practice, no gain in one's wit.
baseurl:      ""
paginate:     1
locale:       "en_US"

# About/contact
author:
  name:       guanguans
  url:        https://guanguans.github.io

# Gems
gems:
  - jekyll-paginate

# Others
markdown: kramdown
