theme: jekyll-theme-cayman

# Setup
title:        guanguans
tagline:      No practice, no gain in one's wit.
baseurl:      ""
paginate:     1
locale:       "en_US"

# About/contact
author:
  name:       琯琯
  url:        https://guanguans.github.io 

# Gems
gems:
  - jekyll-paginate

# Others
markdown: kramdown
